// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: healthcheck/healthcheck/monitored_chains.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MonitoredChain struct {
	ChainId         string                `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ConnectionId    string                `protobuf:"bytes,2,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	Creator         string                `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	TimeoutInterval uint64                `protobuf:"varint,4,opt,name=timeoutInterval,proto3" json:"timeoutInterval,omitempty"`
	UpdateInterval  uint64                `protobuf:"varint,5,opt,name=updateInterval,proto3" json:"updateInterval,omitempty"`
	Status          *MonitoredChainStatus `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *MonitoredChain) Reset()         { *m = MonitoredChain{} }
func (m *MonitoredChain) String() string { return proto.CompactTextString(m) }
func (*MonitoredChain) ProtoMessage()    {}
func (*MonitoredChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d374112fcac9bc6, []int{0}
}
func (m *MonitoredChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonitoredChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonitoredChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonitoredChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitoredChain.Merge(m, src)
}
func (m *MonitoredChain) XXX_Size() int {
	return m.Size()
}
func (m *MonitoredChain) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitoredChain.DiscardUnknown(m)
}

var xxx_messageInfo_MonitoredChain proto.InternalMessageInfo

func (m *MonitoredChain) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *MonitoredChain) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *MonitoredChain) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MonitoredChain) GetTimeoutInterval() uint64 {
	if m != nil {
		return m.TimeoutInterval
	}
	return 0
}

func (m *MonitoredChain) GetUpdateInterval() uint64 {
	if m != nil {
		return m.UpdateInterval
	}
	return 0
}

func (m *MonitoredChain) GetStatus() *MonitoredChainStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type MonitoredChainStatus struct {
	Status              string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp           uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Block               uint64 `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	RegistryBlockHeight uint64 `protobuf:"varint,4,opt,name=registryBlockHeight,proto3" json:"registryBlockHeight,omitempty"`
}

func (m *MonitoredChainStatus) Reset()         { *m = MonitoredChainStatus{} }
func (m *MonitoredChainStatus) String() string { return proto.CompactTextString(m) }
func (*MonitoredChainStatus) ProtoMessage()    {}
func (*MonitoredChainStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d374112fcac9bc6, []int{1}
}
func (m *MonitoredChainStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonitoredChainStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonitoredChainStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonitoredChainStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitoredChainStatus.Merge(m, src)
}
func (m *MonitoredChainStatus) XXX_Size() int {
	return m.Size()
}
func (m *MonitoredChainStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitoredChainStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MonitoredChainStatus proto.InternalMessageInfo

func (m *MonitoredChainStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MonitoredChainStatus) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MonitoredChainStatus) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *MonitoredChainStatus) GetRegistryBlockHeight() uint64 {
	if m != nil {
		return m.RegistryBlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*MonitoredChain)(nil), "healthcheck.healthcheck.MonitoredChain")
	proto.RegisterType((*MonitoredChainStatus)(nil), "healthcheck.healthcheck.MonitoredChainStatus")
}

func init() {
	proto.RegisterFile("healthcheck/healthcheck/monitored_chains.proto", fileDescriptor_9d374112fcac9bc6)
}

var fileDescriptor_9d374112fcac9bc6 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xeb, 0xfe, 0x69, 0x7f, 0xd5, 0xa0, 0x22, 0x99, 0x0a, 0x32, 0x20, 0x53, 0x75, 0x40,
	0x59, 0x08, 0x08, 0x26, 0xd6, 0x22, 0x24, 0x3a, 0xb0, 0x84, 0x8d, 0x05, 0xb9, 0xae, 0xd5, 0x58,
	0x6d, 0xe3, 0xc8, 0xbe, 0x41, 0x74, 0xe4, 0x0d, 0x18, 0x78, 0x28, 0xc6, 0x8e, 0x8c, 0x28, 0x79,
	0x11, 0x14, 0x27, 0x2d, 0x49, 0x55, 0xb6, 0x9c, 0x73, 0xcf, 0x17, 0xf9, 0xde, 0x83, 0xfd, 0x50,
	0xb0, 0x39, 0x84, 0x3c, 0x14, 0x7c, 0x76, 0x51, 0xfd, 0x5e, 0xa8, 0x48, 0x82, 0xd2, 0x62, 0xf2,
	0xcc, 0x43, 0x26, 0x23, 0xe3, 0xc7, 0x5a, 0x81, 0x22, 0xc7, 0x95, 0x4c, 0x95, 0x1d, 0xbc, 0x35,
	0x71, 0xf7, 0x61, 0xcd, 0xdc, 0xe6, 0x08, 0x71, 0xf1, 0x7f, 0xcb, 0x8e, 0x26, 0x2e, 0xea, 0x23,
	0xaf, 0x13, 0xac, 0x25, 0x19, 0xe0, 0x7d, 0xae, 0xa2, 0x48, 0x70, 0x90, 0x2a, 0x1f, 0x37, 0xed,
	0xb8, 0xe6, 0x59, 0x5a, 0x0b, 0x06, 0x4a, 0xbb, 0xff, 0x4a, 0xba, 0x90, 0xc4, 0xc3, 0x07, 0x20,
	0x17, 0x42, 0x25, 0x30, 0x8a, 0x40, 0xe8, 0x17, 0x36, 0x77, 0x9d, 0x3e, 0xf2, 0x9c, 0x60, 0xdb,
	0x26, 0x67, 0xb8, 0x9b, 0xc4, 0x13, 0x06, 0x62, 0x13, 0x6c, 0xd9, 0xe0, 0x96, 0x4b, 0xee, 0x70,
	0xdb, 0x00, 0x83, 0xc4, 0xb8, 0xed, 0x3e, 0xf2, 0xf6, 0xae, 0xce, 0xfd, 0x3f, 0xd6, 0xf4, 0xeb,
	0x2b, 0x3e, 0x5a, 0x28, 0x28, 0xe1, 0xc1, 0x07, 0xc2, 0xbd, 0x5d, 0x01, 0x72, 0xb4, 0xf9, 0x7f,
	0x71, 0x88, 0x52, 0x91, 0x13, 0xdc, 0xc9, 0x9f, 0x6c, 0x80, 0x2d, 0x62, 0x7b, 0x04, 0x27, 0xf8,
	0x35, 0x48, 0x0f, 0xb7, 0xc6, 0x73, 0xc5, 0x67, 0x76, 0x7f, 0x27, 0x28, 0x04, 0xb9, 0xc4, 0x87,
	0x5a, 0x4c, 0xa5, 0x01, 0xbd, 0x1c, 0xe6, 0xc6, 0xbd, 0x90, 0xd3, 0x10, 0xca, 0x0b, 0xec, 0x1a,
	0x0d, 0x6f, 0x3e, 0x53, 0x8a, 0x56, 0x29, 0x45, 0xdf, 0x29, 0x45, 0xef, 0x19, 0x6d, 0xac, 0x32,
	0xda, 0xf8, 0xca, 0x68, 0xe3, 0xe9, 0xb4, 0xda, 0xf8, 0x6b, 0xad, 0x7f, 0x58, 0xc6, 0xc2, 0x8c,
	0xdb, 0xb6, 0xf5, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x2c, 0x76, 0xf8, 0x27, 0x02,
	0x00, 0x00,
}

func (m *MonitoredChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonitoredChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonitoredChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonitoredChains(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.UpdateInterval != 0 {
		i = encodeVarintMonitoredChains(dAtA, i, uint64(m.UpdateInterval))
		i--
		dAtA[i] = 0x28
	}
	if m.TimeoutInterval != 0 {
		i = encodeVarintMonitoredChains(dAtA, i, uint64(m.TimeoutInterval))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMonitoredChains(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintMonitoredChains(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintMonitoredChains(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MonitoredChainStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonitoredChainStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonitoredChainStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegistryBlockHeight != 0 {
		i = encodeVarintMonitoredChains(dAtA, i, uint64(m.RegistryBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.Block != 0 {
		i = encodeVarintMonitoredChains(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x18
	}
	if m.Timestamp != 0 {
		i = encodeVarintMonitoredChains(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintMonitoredChains(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMonitoredChains(dAtA []byte, offset int, v uint64) int {
	offset -= sovMonitoredChains(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MonitoredChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovMonitoredChains(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovMonitoredChains(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMonitoredChains(uint64(l))
	}
	if m.TimeoutInterval != 0 {
		n += 1 + sovMonitoredChains(uint64(m.TimeoutInterval))
	}
	if m.UpdateInterval != 0 {
		n += 1 + sovMonitoredChains(uint64(m.UpdateInterval))
	}
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovMonitoredChains(uint64(l))
	}
	return n
}

func (m *MonitoredChainStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovMonitoredChains(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovMonitoredChains(uint64(m.Timestamp))
	}
	if m.Block != 0 {
		n += 1 + sovMonitoredChains(uint64(m.Block))
	}
	if m.RegistryBlockHeight != 0 {
		n += 1 + sovMonitoredChains(uint64(m.RegistryBlockHeight))
	}
	return n
}

func sovMonitoredChains(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMonitoredChains(x uint64) (n int) {
	return sovMonitoredChains(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MonitoredChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitoredChains
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonitoredChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonitoredChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutInterval", wireType)
			}
			m.TimeoutInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateInterval", wireType)
			}
			m.UpdateInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &MonitoredChainStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonitoredChains(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonitoredChainStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitoredChains
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonitoredChainStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonitoredChainStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryBlockHeight", wireType)
			}
			m.RegistryBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistryBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMonitoredChains(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonitoredChains
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMonitoredChains(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMonitoredChains
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonitoredChains
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMonitoredChains
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMonitoredChains
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMonitoredChains
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMonitoredChains        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMonitoredChains          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMonitoredChains = fmt.Errorf("proto: unexpected end of group")
)
