// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: healthcheck/healthcheck/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89748a99d0ba3c0a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89748a99d0ba3c0a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetMonitoredChainsRequest struct {
	ChainId string `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (m *QueryGetMonitoredChainsRequest) Reset()         { *m = QueryGetMonitoredChainsRequest{} }
func (m *QueryGetMonitoredChainsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMonitoredChainsRequest) ProtoMessage()    {}
func (*QueryGetMonitoredChainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89748a99d0ba3c0a, []int{2}
}
func (m *QueryGetMonitoredChainsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMonitoredChainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMonitoredChainsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMonitoredChainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMonitoredChainsRequest.Merge(m, src)
}
func (m *QueryGetMonitoredChainsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMonitoredChainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMonitoredChainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMonitoredChainsRequest proto.InternalMessageInfo

func (m *QueryGetMonitoredChainsRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type QueryGetMonitoredChainsResponse struct {
	MonitoredChains MonitoredChains `protobuf:"bytes,1,opt,name=monitoredChains,proto3" json:"monitoredChains"`
}

func (m *QueryGetMonitoredChainsResponse) Reset()         { *m = QueryGetMonitoredChainsResponse{} }
func (m *QueryGetMonitoredChainsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMonitoredChainsResponse) ProtoMessage()    {}
func (*QueryGetMonitoredChainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89748a99d0ba3c0a, []int{3}
}
func (m *QueryGetMonitoredChainsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMonitoredChainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMonitoredChainsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMonitoredChainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMonitoredChainsResponse.Merge(m, src)
}
func (m *QueryGetMonitoredChainsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMonitoredChainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMonitoredChainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMonitoredChainsResponse proto.InternalMessageInfo

func (m *QueryGetMonitoredChainsResponse) GetMonitoredChains() MonitoredChains {
	if m != nil {
		return m.MonitoredChains
	}
	return MonitoredChains{}
}

type QueryAllMonitoredChainsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMonitoredChainsRequest) Reset()         { *m = QueryAllMonitoredChainsRequest{} }
func (m *QueryAllMonitoredChainsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMonitoredChainsRequest) ProtoMessage()    {}
func (*QueryAllMonitoredChainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89748a99d0ba3c0a, []int{4}
}
func (m *QueryAllMonitoredChainsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMonitoredChainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMonitoredChainsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMonitoredChainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMonitoredChainsRequest.Merge(m, src)
}
func (m *QueryAllMonitoredChainsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMonitoredChainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMonitoredChainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMonitoredChainsRequest proto.InternalMessageInfo

func (m *QueryAllMonitoredChainsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMonitoredChainsResponse struct {
	MonitoredChains []MonitoredChains   `protobuf:"bytes,1,rep,name=monitoredChains,proto3" json:"monitoredChains"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMonitoredChainsResponse) Reset()         { *m = QueryAllMonitoredChainsResponse{} }
func (m *QueryAllMonitoredChainsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMonitoredChainsResponse) ProtoMessage()    {}
func (*QueryAllMonitoredChainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89748a99d0ba3c0a, []int{5}
}
func (m *QueryAllMonitoredChainsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMonitoredChainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMonitoredChainsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMonitoredChainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMonitoredChainsResponse.Merge(m, src)
}
func (m *QueryAllMonitoredChainsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMonitoredChainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMonitoredChainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMonitoredChainsResponse proto.InternalMessageInfo

func (m *QueryAllMonitoredChainsResponse) GetMonitoredChains() []MonitoredChains {
	if m != nil {
		return m.MonitoredChains
	}
	return nil
}

func (m *QueryAllMonitoredChainsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "healthcheck.healthcheck.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "healthcheck.healthcheck.QueryParamsResponse")
	proto.RegisterType((*QueryGetMonitoredChainsRequest)(nil), "healthcheck.healthcheck.QueryGetMonitoredChainsRequest")
	proto.RegisterType((*QueryGetMonitoredChainsResponse)(nil), "healthcheck.healthcheck.QueryGetMonitoredChainsResponse")
	proto.RegisterType((*QueryAllMonitoredChainsRequest)(nil), "healthcheck.healthcheck.QueryAllMonitoredChainsRequest")
	proto.RegisterType((*QueryAllMonitoredChainsResponse)(nil), "healthcheck.healthcheck.QueryAllMonitoredChainsResponse")
}

func init() {
	proto.RegisterFile("healthcheck/healthcheck/query.proto", fileDescriptor_89748a99d0ba3c0a)
}

var fileDescriptor_89748a99d0ba3c0a = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6b, 0x14, 0x31,
	0x18, 0xc6, 0x37, 0xb5, 0xae, 0x18, 0x0f, 0x85, 0x58, 0xb0, 0x2c, 0x32, 0xa3, 0x51, 0x6c, 0xb5,
	0x92, 0xb0, 0x2d, 0xe2, 0x3f, 0x3c, 0xb4, 0x82, 0xc5, 0x83, 0x50, 0x07, 0x0f, 0xe2, 0x45, 0xb2,
	0xd3, 0x30, 0x33, 0x38, 0x33, 0x99, 0x4e, 0x52, 0xb1, 0x14, 0x2f, 0x9e, 0x3d, 0x08, 0x1e, 0xfc,
	0x2e, 0xde, 0x04, 0x0f, 0x3d, 0x2e, 0x78, 0xf1, 0x24, 0xb2, 0xeb, 0x07, 0x91, 0x4d, 0x32, 0x38,
	0x33, 0x9a, 0xdd, 0x15, 0x7a, 0xcb, 0x6e, 0xde, 0xf7, 0x79, 0x7e, 0x4f, 0xf2, 0x66, 0xe0, 0x95,
	0x98, 0xb3, 0x54, 0xc5, 0x61, 0xcc, 0xc3, 0x57, 0xb4, 0xbe, 0xde, 0x3f, 0xe0, 0xe5, 0x21, 0x29,
	0x4a, 0xa1, 0x04, 0xba, 0x50, 0xdb, 0x20, 0xb5, 0x75, 0x6f, 0x39, 0x12, 0x91, 0xd0, 0x35, 0x74,
	0xb2, 0x32, 0xe5, 0xbd, 0x8b, 0x91, 0x10, 0x51, 0xca, 0x29, 0x2b, 0x12, 0xca, 0xf2, 0x5c, 0x28,
	0xa6, 0x12, 0x91, 0x4b, 0xbb, 0x7b, 0x23, 0x14, 0x32, 0x13, 0x92, 0x0e, 0x98, 0xe4, 0xc6, 0x85,
	0xbe, 0xee, 0x0f, 0xb8, 0x62, 0x7d, 0x5a, 0xb0, 0x28, 0xc9, 0x75, 0xb1, 0xad, 0xbd, 0xea, 0xa2,
	0x2b, 0x58, 0xc9, 0xb2, 0x4a, 0x91, 0xb8, 0xaa, 0x32, 0x91, 0x27, 0x4a, 0x94, 0x7c, 0xef, 0x65,
	0x18, 0xb3, 0xa4, 0x22, 0xc0, 0xcb, 0x10, 0x3d, 0x9d, 0xf8, 0xee, 0x6a, 0x91, 0x80, 0xef, 0x1f,
	0x70, 0xa9, 0xf0, 0x33, 0x78, 0xbe, 0xf1, 0xaf, 0x2c, 0x44, 0x2e, 0x39, 0x7a, 0x00, 0xbb, 0xc6,
	0x6c, 0x05, 0x5c, 0x02, 0x6b, 0xe7, 0x36, 0x7c, 0xe2, 0x38, 0x0c, 0x62, 0x1a, 0xb7, 0x17, 0x8f,
	0x7f, 0xf8, 0x9d, 0xc0, 0x36, 0xe1, 0x7b, 0xd0, 0xd3, 0xaa, 0x3b, 0x5c, 0x3d, 0xa9, 0x68, 0x1e,
	0x6a, 0x18, 0xeb, 0x8b, 0x56, 0xe0, 0x19, 0x4d, 0xf7, 0x78, 0x4f, 0x3b, 0x9c, 0x0d, 0xaa, 0x9f,
	0xf8, 0x08, 0xfa, 0xce, 0x5e, 0x4b, 0xf7, 0x1c, 0x2e, 0x65, 0xcd, 0x2d, 0x8b, 0xb9, 0xe6, 0xc4,
	0x6c, 0x49, 0x59, 0xde, 0xb6, 0x0c, 0x8e, 0x2d, 0xf8, 0x56, 0x9a, 0x3a, 0xc0, 0x1f, 0x41, 0xf8,
	0xe7, 0xc2, 0xac, 0xed, 0x35, 0x62, 0x6e, 0x97, 0x4c, 0x6e, 0x97, 0x98, 0x19, 0xb2, 0xb7, 0x4b,
	0x76, 0x59, 0xc4, 0x6d, 0x6f, 0x50, 0xeb, 0xc4, 0x5f, 0x81, 0xcd, 0xf9, 0x2f, 0xab, 0x69, 0x39,
	0x4f, 0x9d, 0x40, 0x4e, 0xb4, 0xd3, 0x48, 0xb1, 0xa0, 0x53, 0xac, 0xce, 0x4c, 0x61, 0xb0, 0xea,
	0x31, 0x36, 0x3e, 0x2d, 0xc2, 0xd3, 0x3a, 0x06, 0x7a, 0x0f, 0x60, 0xd7, 0x0c, 0x03, 0x5a, 0x77,
	0xe2, 0xfd, 0x3d, 0x81, 0xbd, 0x9b, 0xf3, 0x15, 0x1b, 0x6f, 0xbc, 0xfa, 0xee, 0xdb, 0xaf, 0x8f,
	0x0b, 0x97, 0x91, 0x4f, 0xa7, 0x3f, 0x12, 0xf4, 0x05, 0xc0, 0xa5, 0xd6, 0x61, 0xa0, 0xdb, 0xd3,
	0xad, 0x9c, 0xd3, 0xda, 0xbb, 0xf3, 0xff, 0x8d, 0x96, 0xf7, 0xbe, 0xe6, 0xbd, 0x85, 0x36, 0xe9,
	0xbc, 0xcf, 0x95, 0x1e, 0xd9, 0x97, 0xf0, 0x16, 0x7d, 0x06, 0x10, 0xb5, 0x84, 0xb7, 0xd2, 0x74,
	0x56, 0x0c, 0xe7, 0xec, 0xce, 0x8a, 0xe1, 0x9e, 0x44, 0xdc, 0xd7, 0x31, 0xd6, 0xd1, 0xf5, 0xb9,
	0x63, 0x6c, 0xdf, 0x3d, 0x1e, 0x79, 0x60, 0x38, 0xf2, 0xc0, 0xcf, 0x91, 0x07, 0x3e, 0x8c, 0xbd,
	0xce, 0x70, 0xec, 0x75, 0xbe, 0x8f, 0xbd, 0xce, 0x0b, 0xbf, 0xde, 0xf7, 0xa6, 0xa1, 0xa2, 0x0e,
	0x0b, 0x2e, 0x07, 0x5d, 0xfd, 0xc5, 0xda, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x85, 0x6e, 0x98,
	0x3d, 0xa7, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of MonitoredChains items.
	MonitoredChains(ctx context.Context, in *QueryGetMonitoredChainsRequest, opts ...grpc.CallOption) (*QueryGetMonitoredChainsResponse, error)
	MonitoredChainsAll(ctx context.Context, in *QueryAllMonitoredChainsRequest, opts ...grpc.CallOption) (*QueryAllMonitoredChainsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/healthcheck.healthcheck.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MonitoredChains(ctx context.Context, in *QueryGetMonitoredChainsRequest, opts ...grpc.CallOption) (*QueryGetMonitoredChainsResponse, error) {
	out := new(QueryGetMonitoredChainsResponse)
	err := c.cc.Invoke(ctx, "/healthcheck.healthcheck.Query/MonitoredChains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MonitoredChainsAll(ctx context.Context, in *QueryAllMonitoredChainsRequest, opts ...grpc.CallOption) (*QueryAllMonitoredChainsResponse, error) {
	out := new(QueryAllMonitoredChainsResponse)
	err := c.cc.Invoke(ctx, "/healthcheck.healthcheck.Query/MonitoredChainsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of MonitoredChains items.
	MonitoredChains(context.Context, *QueryGetMonitoredChainsRequest) (*QueryGetMonitoredChainsResponse, error)
	MonitoredChainsAll(context.Context, *QueryAllMonitoredChainsRequest) (*QueryAllMonitoredChainsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) MonitoredChains(ctx context.Context, req *QueryGetMonitoredChainsRequest) (*QueryGetMonitoredChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitoredChains not implemented")
}
func (*UnimplementedQueryServer) MonitoredChainsAll(ctx context.Context, req *QueryAllMonitoredChainsRequest) (*QueryAllMonitoredChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitoredChainsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheck.healthcheck.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MonitoredChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMonitoredChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MonitoredChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheck.healthcheck.Query/MonitoredChains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MonitoredChains(ctx, req.(*QueryGetMonitoredChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MonitoredChainsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMonitoredChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MonitoredChainsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheck.healthcheck.Query/MonitoredChainsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MonitoredChainsAll(ctx, req.(*QueryAllMonitoredChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "healthcheck.healthcheck.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "MonitoredChains",
			Handler:    _Query_MonitoredChains_Handler,
		},
		{
			MethodName: "MonitoredChainsAll",
			Handler:    _Query_MonitoredChainsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "healthcheck/healthcheck/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMonitoredChainsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMonitoredChainsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMonitoredChainsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMonitoredChainsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMonitoredChainsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMonitoredChainsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MonitoredChains.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMonitoredChainsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMonitoredChainsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMonitoredChainsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMonitoredChainsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMonitoredChainsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMonitoredChainsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MonitoredChains) > 0 {
		for iNdEx := len(m.MonitoredChains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MonitoredChains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMonitoredChainsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMonitoredChainsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MonitoredChains.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMonitoredChainsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMonitoredChainsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MonitoredChains) > 0 {
		for _, e := range m.MonitoredChains {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMonitoredChainsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMonitoredChainsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMonitoredChainsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMonitoredChainsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMonitoredChainsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMonitoredChainsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonitoredChains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MonitoredChains.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMonitoredChainsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMonitoredChainsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMonitoredChainsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMonitoredChainsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMonitoredChainsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMonitoredChainsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonitoredChains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MonitoredChains = append(m.MonitoredChains, MonitoredChains{})
			if err := m.MonitoredChains[len(m.MonitoredChains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
